### ISSUE TITLE
npm run dev:h5报如下错误怎么处理

### ISSUE THREAD

**Issue by xiaoqing0729** [SummerSnake/taro-mall#1]
(node:20700) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'uglify' of undefined
    at Object.default_1 [as default] (D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\config\dll.conf.js:19:38)
    at D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:43:48
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:42:12)
    at Generator.next (<anonymous>)
    at D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:3:12)
    at buildDll (D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:39:30)
    at Object.<anonymous> (D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:130:15)
    at Generator.next (<anonymous>)
    at D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:3:12)
    at exports.default (D:\workspace_front\taro-mall\node_modules\_@tarojs_webpack-runner@1.2.16@@tarojs\webpack-runner\dist\index.js:125:31)
    at Compiler.<anonymous> (D:\Program Files\nodejs\npm-g\node_modules\@tarojs\cli\dist\h5\index.js:150:13)
(node:20700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xiaoqing0729** [comment]
![image](https://user-images.githubusercontent.com/16095288/62860631-52b3af00-bd33-11e9-8ba9-5554c28b2e5e.png)

**Comment by SummerSnake** [comment]
没做 H5 端，只做了小程序端。
